#!/bin/bash

INRES="1920x1080"
OUTRES="1280x720"
FPS="20"
QUAL="medium"
FONT="/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf"
STREAM_KEY=$(cat ~/.twitch_key)

avconv -g 0 \
    -f x11grab -s $INRES -r "$FPS" -i :0.0+0,768 \
    -f pulse -i alsa_input.pci-0000_00_1b.0.analog-stereo \
    -vcodec libx264 -s $OUTRES -preset $QUAL \
    -acodec libmp3lame -ar 44100 -threads 4 -qscale 1 -b 712k -bufsize 1024k \
    -vf drawtext="fontfile=$FONT: text='Soulstitchmmo Gaming on Ubuntu 14.04':\
    x=950: y=950: fontsize=48: fontcolor=white@0.2" \
    -f flv "rtmp://live.justin.tv/app/$STREAM_KEY"
