#!/bin/bash
## The following is a script for streaming to twitch.tv if you have any questions send me an email at michaeljwjr@gmail.com
## Written in Ubuntu 14.04, other distros/setups will have to adapt script to their setup
##
## Contact Information
## Twitch channel twitch.tv/soulstitchmmo
## Personal G+ https://plus.google.com/106295000788676760101/posts
## Gaming on Linux Google Community:  https://plus.google.com/communities/107473457673091339260


### Settings ###
### INRES is the resolution of the desktp you're capturing from
### OUTRES is the resolution you want to broadcast to, I found 1280x720 to be a fair HD setting
### FPS set to what you like 20 works just fine for me but you can raise this or lower this depending on your hardware
### Qual preset can be set to veryslow, slow, medium, fast, veryfast (among others) veryslow is best quality
### You can add as many logo's as you like using the overlay information found here: 
### http://manpages.ubuntu.com/manpages/trusty/en/man1/avconv.1.html

INRES="1920x1080"
OUTRES="1280x720"
WEBSIZE="qvga"
FPS="20"
QUAL="veryfast" 
LOGO1="/home/michaeljwjr/Pictures/graveldogfaded.png"
LOGO2="/home/michaeljwjr/Pictures/soulstitchmmo.png"

### you must create a .twitch_key file and paste your twitch key there
### you can get your twitch key from http://www.twitch.tv/<YOUR_USERNAME>/dashboard/streamkey

STREAM_KEY=$(cat ~/twitchstream/.twitch_key)

### Stream Command ###
### x11grab records your desktop. :0.0 is the top left hand corner of the screen
### the +0,768 moves the top corner of the screen to my bottom monitor, you can remove this if you 
### are only using one monitor. Or change this depending on the location of your second monitor.
### (my top montior is 1360x768)
### I found that using alsa was giving my terrible mic quality so I switched to pulse device directly
### in terminal type: 
### pactl list sources | grep Name:
### to find the list of audio sources. The top choice is my mic(input) and my desktop(output). Use 
### pavucontrol (sudo apt-get install pavucontrol) to make sure you're recording buil-in audio and
### monitor of built-in audio to get mic and desktop respectively. change -qscale, -b and -bufsize 
### to adjust quality. 

avconv \
    -f x11grab -s $INRES -framerate "$FPS" -i :0.0+0,768 \
    -f video4linux2 -video_size $WEBSIZE \
    -i /dev/video0 \
    -i $LOGO1 \
    -i $LOGO2 \
    -filter_complex 'overlay=10:H-h-820,overlay=10:H-h-10,overlay=1170:H-h-20' \
    -f pulse -i "Virtual1.monitor" \
    -vcodec libx264 -s $OUTRES -preset $QUAL \
    -acodec libmp3lame -ar 44100 -threads 4 -qscale 5 -b 2048k -bufsize 512k \
    -f flv rtmp://live.justin.tv/app/$STREAM_KEY \

### For further reading please check out the man page for avconv or visit libav.org/avconv.html
### Or visit http://manpages.ubuntu.com/manpages/trusty/en/man1/avconv.1.html
